deployment:
  replicas: 1
  image:
    repository: ghcr.io/igorgolm/aws-cd-georgia-demo-app ## !! Update this to your image repository ##
    tag: 9e7f94ab66dca5e8149c92d5a716d5904b8d8d37 ## !! Update this to your image tag ##
  imagePullPolicy: IfNotPresent
  serviceAccount: default
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 100Mi
  readinessProbe:
    httpGet:
      path: /healthz
      port: 8080
    initialDelaySeconds: 2
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 15
    timeoutSeconds: 3
    failureThreshold: 3

service:
  type: ClusterIP
  ports:
    name: http
    port: 80
    targetPort: 8080


