apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aws-cd-georgia-demo-app.fullname" . }}
  labels:
    app: {{ .Release.Name }}
  {{- include "aws-cd-georgia-demo-app.labels" . | nindent 2 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
    {{- include "aws-cd-georgia-demo-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      {{- include "aws-cd-georgia-demo-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.deployment.serviceAccount }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        ports:
        - containerPort: 8080
          name: http
        readinessProbe: {{- toYaml .Values.deployment.readinessProbe | nindent 10 }}
        livenessProbe: {{- toYaml .Values.deployment.livenessProbe | nindent 10 }}
        resources: {{- toYaml .Values.deployment.resources | nindent 10 }}


